plugins:
  tslint:
    enabled: true
    config: tslint.json
  markdownlint:
    enabled: false
  fixme:
    enabled: true

exclude_patterns:
- "test/"
- "postman/"
- "**/node_modules/"
- "dist/"
- "coverage/"

