name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: integration testing
      run: npm run test:integration
    - name: Coveralls reporting
      run: npm run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_SECRET }}
        COVERALLS_SERVICE_NAME: Github Actions main.workflow
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=doppelganger9-github
          -Dsonar.projectKey=doppelganger9_babyfoot
          -Dsonar.typescript.exclusions=**/node_modules/** 
          -Dsonar.exclusions=node_modules/**/*,coverage/**/*,reports/**/*,**/*.config.js,**/*.conf.js
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info          
          -Dsonar.language=ts
          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*.spec.ts
          -Dsonar.typescript.tsconfigPath=tsconfig.json
          -Dsonar.sources=.
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - run: npm run test:mutations
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
